# Generated by Django 5.2.1 on 2025-09-14 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Categoría')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion del producto')),
                ('unidad', models.CharField(choices=[('0', 'Kilogramos'), ('1', 'Litros'), ('2', 'Unidades')], max_length=1, verbose_name='Unidad de medida')),
                ('cantidad', models.PositiveBigIntegerField(default=0, verbose_name='Cantidad en Almacen')),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio de Compra')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio de Venta')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/product/')),
                ('visible_en_tienda', models.BooleanField(default=True)),
                ('disponible', models.BooleanField(default=True, verbose_name='¿Disponible?')),
                ('es_nuevo', models.BooleanField(default=False, verbose_name='¿Nuevo?')),
                ('en_oferta', models.BooleanField(default=False, verbose_name='¿En oferta?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
