# Generated by Django 5.2.7 on 2025-10-29 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Cantidad en Almacen'),
        ),
    ]
