# Generated by Django 5.2.7 on 2026-03-28 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_producto_cantidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
