# Generated by Django 5.2.1 on 2025-09-14 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_venta', to=settings.AUTH_USER_MODEL, verbose_name='cajero'),
        ),
        migrations.AddField(
            model_name='pagoventa',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_aplicados', to='sales.venta'),
        ),
        migrations.AddField(
            model_name='historialsaldo',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.venta'),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='VD_VentasId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sales.venta'),
        ),
        migrations.AddField(
            model_name='ventadetalle',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sale', to='product.producto', verbose_name='producto'),
        ),
        migrations.AlterUniqueTogether(
            name='pagoventa',
            unique_together={('pago', 'venta')},
        ),
    ]
