# Generated by Django 5.2.6 on 2025-09-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='Venta_cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad de Producto'),
        ),
    ]
