# Generated by Django 5.2.1 on 2025-09-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventadetalle',
            name='VD_Cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad'),
        ),
    ]
