# Generated by Django 5.2.6 on 2025-09-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_venta_venta_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='carshop',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
