# Generated by Django 5.2.1 on 2025-09-16 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_ventadetalle_vd_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carshop',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
