# Generated by Django 5.2.7 on 2025-11-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_carshop_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='anulate',
            field=models.BooleanField(default=False, verbose_name='Venta Anulada'),
        ),
    ]
