# Generated by Django 5.2.7 on 2026-03-17 02:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('sales', '0005_venta_anulate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-created'], 'verbose_name': 'Ventas'},
        ),
        migrations.RemoveField(
            model_name='venta',
            name='anulate',
        ),
        migrations.AddField(
            model_name='venta',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('confirmed', 'Confirmada'), ('cancelled', 'Anulada')], default='draft', max_length=10),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['user', 'Venta_Fecha'], name='sales_venta_user_id_a7b696_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['Venta_CliId'], name='sales_venta_Venta_C_24d07b_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['status'], name='sales_venta_status_90708c_idx'),
        ),
    ]
