# Generated by Django 5.2.7 on 2026-03-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_carshop_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventadetalle',
            name='VD_precio_compra',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
            preserve_default=False,
        ),
    ]
